### ISSUE TITLE
How i can set includePath?

### ISSUE THREAD

**Issue by MrFranke** [sp00m/gulp-watch-sass#6]
For compass and other libs

**Comment by sp00m** [comment]
What are you trying to solve? Any documentation about this option?

**Comment by MrFranke** [comment]
I have SASS project with compass and [incudePath](https://github.com/sass/node-sass#includepaths) option. When watchSass rebuild scss files i got an error `cant resolve path 'compass/..'`, but if I compile scss with `gulp-sass` task i haven't any errors.

**Comment by sp00m** [comment]
Thanks, this is not yet possible with `gulp-watch-sass`, but I'm happy adding this. I gonna start working on this when I find some free time, probably this weekend.

In the mean time, it would be great if you could provide your project structure (folders, files locations, etc.), plus your gulpfile.js, so that I can replicate your exact issue.

**Comment by MrFranke** [comment]
Sorry, it's NDA project, but I can reproduce this case in test repo in this weekends.

**Comment by MrFranke** [comment]
@sp00m hey! Sorry for long answer.
I created test repo for problem: https://github.com/MrFranke/gulp-watch-sass-test

**Comment by sp00m** [comment]
Thanks for having taken the time to build this MVCE, working on it!

**Comment by sp00m** [comment]
Should be fixed now, check version 1.3.0. Thanks for the MVCE, definitely helped!

**Comment by sp00m** [comment]
Usage: https://github.com/sp00m/gulp-watch-sass/blob/master/README.md#optionsincludepaths
